import unittest
from unittest.mock import patch

from app.services.hybrid_parser_service import parse_user_query_hybrid
from app.services.query_parser_service import parse_user_query


class ParserBehaviorTests(unittest.TestCase):
    def test_parse_open_tasks_by_client(self):
        parsed = parse_user_query("que tengo pendiente con Cam")
        self.assertEqual(parsed["intent"], "get_open_tasks_by_client_name")
        self.assertEqual(parsed["client_name"], "cam")

    def test_parse_task_status_update(self):
        parsed = parse_user_query("marca onboarding como en progreso")
        self.assertEqual(parsed["intent"], "update_task_status")
        self.assertEqual(parsed["task_name"], "onboarding")
        self.assertEqual(parsed["new_status"], "en_progreso")

    def test_parse_task_note_update(self):
        parsed = parse_user_query("agrega una nota a onboarding: falta validar")
        self.assertEqual(parsed["intent"], "add_task_note")
        self.assertEqual(parsed["task_name"], "onboarding")
        self.assertEqual(parsed["last_note"], "falta validar")

    def test_parse_executive_queries(self):
        blocked = parse_user_query("que esta bloqueado")
        today = parse_user_query("que deberia hacer hoy")
        self.assertEqual(blocked["intent"], "get_blocked_items_summary")
        self.assertEqual(today["intent"], "get_today_priority_summary")

    def test_parse_followup_queries(self):
        client_followup = parse_user_query("que sigue para este cliente")
        missing_next = parse_user_query("que tareas no tienen proxima accion")
        push_today = parse_user_query("que deberia empujar hoy si o si")
        self.assertEqual(client_followup["intent"], "get_next_actions_summary")
        self.assertEqual(client_followup["client_name"], "este cliente")
        self.assertEqual(missing_next["intent"], "get_missing_next_actions_summary")
        self.assertEqual(push_today["intent"], "get_push_today_summary")

    def test_parse_operational_summary_queries(self):
        client = parse_user_query("comentame en que andamos con Cam")
        project = parse_user_query("como viene dashboard")
        contextual = parse_user_query("que es lo mas importante aca")
        focused_client = parse_user_query("que es lo mas importante respecto a rosario capilar?")
        self.assertEqual(client["intent"], "get_operational_summary")
        self.assertEqual(client["entity_hint"], "cam")
        self.assertEqual(project["intent"], "get_operational_summary")
        self.assertEqual(project["entity_hint"], "dashboard")
        self.assertEqual(contextual["intent"], "get_operational_summary")
        self.assertEqual(focused_client["intent"], "get_operational_summary")
        self.assertEqual(focused_client["client_name"], "rosario capilar")
        self.assertEqual(focused_client["expected_scope"], "client")

    def test_parse_operational_friction_queries(self):
        stalled = parse_user_query("que viene estancado")
        real_stalled = parse_user_query("que me viene estancando")
        risky_client = parse_user_query("que me preocuparia de Cam")
        contextual = parse_user_query("y que esta frenado?")
        self.assertEqual(stalled["intent"], "get_operational_friction_summary")
        self.assertEqual(real_stalled["intent"], "get_operational_friction_summary")
        self.assertEqual(risky_client["intent"], "get_operational_friction_summary")
        self.assertEqual(risky_client["entity_hint"], "cam")
        self.assertEqual(contextual["intent"], "get_operational_friction_summary")

    def test_parse_operational_recommendation_queries(self):
        client = parse_user_query("que me recomendas hacer con Cam")
        real_client = parse_user_query("que harias ahora con Cam")
        contextual_followup = parse_user_query("que harias ahora")
        contextual_recommend = parse_user_query("que me recomendarias hacer ahora")
        first = parse_user_query("que atacaria primero")
        choose_one = parse_user_query("si tuvieras que elegir una sola tarea, cual seria")
        close = parse_user_query("que conviene cerrar hoy")
        contextual = parse_user_query("que priorizarias en este proyecto")
        self.assertEqual(client["intent"], "get_operational_recommendation")
        self.assertEqual(client["entity_hint"], "cam")
        self.assertEqual(real_client["intent"], "get_operational_recommendation")
        self.assertEqual(real_client["entity_hint"], "cam")
        self.assertEqual(contextual_followup["intent"], "get_operational_recommendation")
        self.assertEqual(contextual_followup["entity_hint"], "aca")
        self.assertEqual(contextual_recommend["intent"], "get_operational_recommendation")
        self.assertEqual(contextual_recommend["entity_hint"], "aca")
        self.assertEqual(first["intent"], "get_operational_recommendation")
        self.assertEqual(first["recommendation_focus"], "general")
        self.assertEqual(choose_one["recommendation_focus"], "general")
        self.assertEqual(close["recommendation_focus"], "close")
        self.assertEqual(contextual["project_name"], "este proyecto")

    def test_parse_active_projects_query(self):
        parsed = parse_user_query("proyectos activos")
        self.assertEqual(parsed["intent"], "get_active_projects")

    def test_parse_conversational_drilldown_queries(self):
        why = parse_user_query("por que esa")
        next_one = parse_user_query("y despues de eso?")
        critical = parse_user_query("mostrame solo lo critico")
        short = parse_user_query("resumimelo en 3 lineas")
        client_facing = parse_user_query("que le diria al cliente hoy")
        self.assertEqual(why["intent"], "get_recommendation_explanation")
        self.assertEqual(next_one["intent"], "get_followup_focus_summary")
        self.assertEqual(next_one["followup_focus"], "next_after_recommendation")
        self.assertEqual(critical["intent"], "get_filtered_context_summary")
        self.assertEqual(critical["filter_mode"], "critical")
        self.assertEqual(short["intent"], "get_rephrased_summary")
        self.assertEqual(short["rephrase_style"], "three_lines")
        self.assertEqual(client_facing["intent"], "get_client_facing_summary")

    def test_parse_adaptive_output_queries(self):
        short = parse_user_query("damelo corto")
        executive = parse_user_query("damelo ejecutivo")
        tactical = parse_user_query("damelo tactico")
        detailed = parse_user_query("quiero mas detalle")
        risks = parse_user_query("quiero solo riesgos")
        next_steps = parse_user_query("quiero solo proximos pasos")
        bullets = parse_user_query("dame solo bullets")
        meeting = parse_user_query("decimelo como para reunion")
        personal = parse_user_query("decimelo como para mi")
        important = parse_user_query("mostrame solo lo importante")
        client = parse_user_query("decimelo como para mandarselo al cliente")

        self.assertEqual(short["intent"], "get_rephrased_summary")
        self.assertEqual(short["rephrase_style"], "short")
        self.assertEqual(executive["rephrase_style"], "executive")
        self.assertEqual(tactical["rephrase_style"], "tactical")
        self.assertEqual(detailed["rephrase_style"], "detailed")
        self.assertEqual(risks["intent"], "get_filtered_context_summary")
        self.assertEqual(risks["filter_mode"], "risks")
        self.assertEqual(next_steps["filter_mode"], "next_steps")
        self.assertEqual(bullets["rephrase_style"], "bullets")
        self.assertEqual(meeting["rephrase_style"], "meeting_ready")
        self.assertEqual(personal["rephrase_style"], "personal")
        self.assertEqual(important["filter_mode"], "important")
        self.assertEqual(client["intent"], "get_client_facing_summary")

    def test_parse_creation_queries(self):
        create_task = parse_user_query("crea una tarea para revisar indicadores")
        create_for_client = parse_user_query("agrega una tarea a Cam para definir metricas")
        create_in_project = parse_user_query("agrega una tarea en este proyecto")
        create_natural_client = parse_user_query("agregame una tarea a cam: hacer revision anual")
        create_natural_project = parse_user_query("agregame una tarea a el proyecto automatizacion de cam: hacer revision anual")
        project_note = parse_user_query("suma una nota al proyecto: falta validacion")
        project_note_without_content = parse_user_query("suma una nota al proyecto")
        next_action = parse_user_query("dejame una proxima accion para manana")
        convert = parse_user_query("converti esto en tarea")
        create_tomorrow = parse_user_query("crea una tarea para revisar indicadores para manana")
        create_urgent_today = parse_user_query("agrega una tarea urgente para revisar backlog para hoy")
        followup_friday = parse_user_query("deja follow-up para el viernes")

        self.assertEqual(create_task["intent"], "create_task")
        self.assertEqual(create_task["task_name"], "revisar indicadores")
        self.assertEqual(create_for_client["intent"], "create_task")
        self.assertEqual(create_for_client["client_name"], "cam")
        self.assertEqual(create_for_client["task_name"], "definir metricas")
        self.assertEqual(create_in_project["intent"], "create_task")
        self.assertEqual(create_in_project["project_name"], "este proyecto")
        self.assertEqual(create_natural_client["intent"], "create_task")
        self.assertEqual(create_natural_client["client_name"], "cam")
        self.assertEqual(create_natural_client["task_name"], "hacer revision anual")
        self.assertEqual(create_natural_project["intent"], "create_task")
        self.assertEqual(create_natural_project["project_name"], "automatizacion")
        self.assertEqual(create_natural_project["client_name"], "cam")
        self.assertEqual(create_natural_project["task_name"], "hacer revision anual")
        self.assertEqual(project_note["intent"], "add_project_note")
        self.assertEqual(project_note["last_note"], "falta validacion")
        self.assertEqual(project_note_without_content["intent"], "add_project_note")
        self.assertIsNone(project_note_without_content["last_note"])
        self.assertEqual(next_action["intent"], "update_task_next_action")
        self.assertEqual(next_action["next_action"], "manana")
        self.assertEqual(convert["intent"], "create_task")
        self.assertEqual(convert["task_name"], "esto")
        self.assertEqual(create_tomorrow["due_hint"], "manana")
        self.assertEqual(create_tomorrow["time_scope"], "tomorrow")
        self.assertEqual(create_urgent_today["task_name"], "revisar backlog")
        self.assertEqual(create_urgent_today["new_priority"], "alta")
        self.assertEqual(create_urgent_today["due_hint"], "hoy")
        self.assertEqual(followup_friday["intent"], "create_followup")
        self.assertEqual(followup_friday["due_hint"], "viernes")

    def test_parse_temporal_queries(self):
        due_today = parse_user_query("que vence hoy")
        overdue = parse_user_query("que tengo atrasado")
        tomorrow = parse_user_query("que tengo para manana")
        week_followups = parse_user_query("que follow-ups vencen esta semana")
        missing_due = parse_user_query("que no tiene fecha y deberia tenerla")

        self.assertEqual(due_today["intent"], "get_due_tasks_summary")
        self.assertEqual(due_today["time_scope"], "today")
        self.assertEqual(overdue["intent"], "get_overdue_tasks_summary")
        self.assertEqual(overdue["time_scope"], "overdue")
        self.assertEqual(tomorrow["intent"], "get_due_tasks_summary")
        self.assertEqual(tomorrow["time_scope"], "tomorrow")
        self.assertEqual(week_followups["temporal_focus"], "followups")
        self.assertEqual(missing_due["intent"], "get_missing_due_date_summary")

    def test_parse_agenda_queries(self):
        create_event = parse_user_query("agendame manana a las 10 una reunion con Cam")
        create_reminder = parse_user_query("recordame manana revisar indicadores")
        create_friday = parse_user_query("agendame para el viernes a las 16 llamar a Rosario Capilar")
        missing_date = parse_user_query("agendame revisar indicadores")
        today = parse_user_query("que tengo para hoy")
        tomorrow = parse_user_query("que tengo manana")
        week = parse_user_query("que tengo esta semana")
        at_time = parse_user_query("que tengo a las 10")
        after_current = parse_user_query("que tengo despues")
        boolean_query = parse_user_query("tengo algo manana")

        self.assertEqual(create_event["intent"], "create_agenda_item")
        self.assertEqual(create_event["agenda_kind"], "event")
        self.assertEqual(create_event["agenda_date_hint"], "manana")
        self.assertEqual(create_event["agenda_time_hint"], "10")
        self.assertEqual(create_event["agenda_title"], "reunion con cam")
        self.assertEqual(create_reminder["agenda_kind"], "reminder")
        self.assertEqual(create_reminder["agenda_date_hint"], "manana")
        self.assertEqual(create_friday["agenda_date_hint"], "viernes")
        self.assertEqual(create_friday["agenda_time_hint"], "16")
        self.assertEqual(missing_date["intent"], "create_agenda_item")
        self.assertIsNone(missing_date["agenda_date_hint"])
        self.assertEqual(today["intent"], "get_agenda_items_summary")
        self.assertEqual(today["agenda_query_scope"], "today")
        self.assertEqual(tomorrow["agenda_query_scope"], "tomorrow")
        self.assertEqual(week["agenda_query_scope"], "this_week")
        self.assertEqual(at_time["agenda_query_scope"], "at_time")
        self.assertEqual(at_time["agenda_time_hint"], "10")
        self.assertEqual(after_current["agenda_query_scope"], "after_current")
        self.assertTrue(boolean_query["agenda_boolean_query"])

    def test_parse_agenda_crud_queries(self):
        delete_event = parse_user_query("borra la reunion de manana")
        delete_reminder = parse_user_query("cancela el recordatorio de revisar indicadores")
        delete_context = parse_user_query("borra eso")
        reschedule_time = parse_user_query("cambia la reunion de manana de las 11 a las 12")
        reschedule_date_time = parse_user_query("reprograma el dentista para el viernes a las 18")
        move_context = parse_user_query("pasa eso para manana")
        move_time = parse_user_query("move la reunion a las 15")

        self.assertEqual(delete_event["intent"], "delete_agenda_item")
        self.assertEqual(delete_event["agenda_target_title"], "reunion")
        self.assertEqual(delete_event["agenda_target_date_hint"], "manana")
        self.assertEqual(delete_reminder["intent"], "delete_agenda_item")
        self.assertEqual(delete_reminder["agenda_target_kind"], "reminder")
        self.assertTrue(delete_context["agenda_use_context"])
        self.assertEqual(reschedule_time["intent"], "update_agenda_item")
        self.assertEqual(reschedule_time["agenda_target_time_hint"], "11")
        self.assertEqual(reschedule_time["agenda_new_time_hint"], "12")
        self.assertEqual(reschedule_date_time["agenda_target_title"], "dentista")
        self.assertEqual(reschedule_date_time["agenda_new_date_hint"], "viernes")
        self.assertEqual(reschedule_date_time["agenda_new_time_hint"], "18")
        self.assertTrue(move_context["agenda_use_context"])
        self.assertEqual(move_time["agenda_new_time_hint"], "15")

    def test_parse_compound_queries(self):
        summary_and_recommend = parse_user_query("resumime Cam y decime que haria primero")
        temporal_and_friction = parse_user_query("que vence y que me preocuparia")
        urgent_and_overdue = parse_user_query("que tengo urgente y atrasado")
        summary_and_followup = parse_user_query("comentame dashboard y despues decime que sigue")
        client_facing = parse_user_query("que me preocuparia de Cam y que le diria al cliente")

        self.assertEqual(summary_and_recommend["intent"], "compound_query")
        self.assertEqual(summary_and_recommend["subqueries"][0]["intent"], "get_operational_summary")
        self.assertEqual(summary_and_recommend["subqueries"][1]["intent"], "get_operational_recommendation")
        self.assertEqual(temporal_and_friction["subqueries"][0]["intent"], "get_due_tasks_summary")
        self.assertEqual(temporal_and_friction["subqueries"][1]["intent"], "get_followup_focus_summary")
        self.assertEqual(urgent_and_overdue["subqueries"][0]["intent"], "get_today_priority_summary")
        self.assertEqual(urgent_and_overdue["subqueries"][1]["intent"], "get_overdue_tasks_summary")
        self.assertEqual(summary_and_followup["subqueries"][1]["intent"], "get_next_actions_summary")
        self.assertEqual(client_facing["subqueries"][1]["intent"], "get_client_facing_summary")

    def test_parse_fine_targeting_queries(self):
        summary = parse_user_query("resumime el dashboard de ventas, no el otro")
        friction = parse_user_query("que me preocuparia del proyecto de automatizacion de Cam")
        create_task = parse_user_query("agrega una tarea al proyecto de dashboard comercial")
        project_summary = parse_user_query("comentame el proyecto de onboarding de Cam")
        followup_choice = parse_user_query("el de ventas")
        in_project_choice = parse_user_query("en dashboard comercial")
        short_choice = parse_user_query("el comercial")

        self.assertEqual(summary["intent"], "get_operational_summary")
        self.assertEqual(summary["entity_hint"], "dashboard de ventas")
        self.assertEqual(summary["secondary_descriptor"], "de ventas")
        self.assertEqual(summary["contrast_hint"], "exclude_other")
        self.assertEqual(friction["intent"], "get_operational_friction_summary")
        self.assertEqual(friction["project_name"], "automatizacion")
        self.assertEqual(friction["client_name"], "cam")
        self.assertEqual(friction["expected_scope"], "project")
        self.assertEqual(create_task["intent"], "create_task")
        self.assertEqual(create_task["project_name"], "dashboard comercial")
        self.assertEqual(create_task["expected_scope"], "project")
        self.assertEqual(project_summary["project_name"], "onboarding")
        self.assertEqual(project_summary["client_name"], "cam")
        self.assertEqual(followup_choice["intent"], "clarify_entity_reference")
        self.assertTrue(followup_choice["use_previous_candidates"])
        self.assertEqual(in_project_choice["intent"], "clarify_entity_reference")
        self.assertTrue(in_project_choice["use_previous_candidates"])
        self.assertEqual(in_project_choice["entity_hint"], "dashboard comercial")
        self.assertEqual(short_choice["intent"], "clarify_entity_reference")
        self.assertTrue(short_choice["use_previous_candidates"])

    def test_parse_audit_queries(self):
        recent = parse_user_query("que hiciste recien")
        resolution = parse_user_query("que resolviste")
        reason = parse_user_query("por que elegiste esa")
        blocked = parse_user_query("que quedo bloqueado por seguridad")
        understood = parse_user_query("que parte entendiste")
        action = parse_user_query("que accion ejecutaste")

        self.assertEqual(recent["intent"], "get_audit_trace_summary")
        self.assertEqual(recent["audit_focus"], "recent")
        self.assertEqual(resolution["audit_focus"], "resolution")
        self.assertEqual(reason["audit_focus"], "decision_reason")
        self.assertEqual(blocked["audit_focus"], "blocked")
        self.assertEqual(understood["audit_focus"], "understood")
        self.assertEqual(action["audit_focus"], "action")

    def test_parse_contextual_followups(self):
        projects = parse_user_query("y sus proyectos?")
        close_task = parse_user_query("cerrala")
        self.assertEqual(projects["intent"], "get_projects_by_client_name")
        self.assertEqual(projects["client_name"], "este cliente")
        self.assertEqual(close_task["intent"], "update_task_status")
        self.assertEqual(close_task["task_name"], "eso")

    def test_parse_open_ambiguous_inputs_as_clarification(self):
        dashboard = parse_user_query("dashboard")
        view_cam = parse_user_query("quiero ver Cam")
        summary_dashboard = parse_user_query("resumime lo del dashboard")
        self.assertEqual(dashboard["intent"], "clarify_entity_reference")
        self.assertEqual(dashboard["entity_hint"], "dashboard")
        self.assertEqual(view_cam["intent"], "clarify_entity_reference")
        self.assertEqual(view_cam["entity_hint"], "cam")
        self.assertEqual(summary_dashboard["intent"], "clarify_entity_reference")
        self.assertEqual(summary_dashboard["entity_hint"], "dashboard")

    def test_hybrid_prefers_rules_for_short_updates(self):
        llm_result = {
            "intent": "get_task_summary",
            "task_name": "otra cosa",
            "_parser_source": "llm",
        }
        with patch("app.services.hybrid_parser_service.parse_query_with_llm", return_value=llm_result):
            parsed = parse_user_query_hybrid("cerrala")
        self.assertEqual(parsed["intent"], "update_task_status")
        self.assertEqual(parsed["_parser_source"], "rules")
        self.assertEqual(parsed["_parser_decision"], "rules_over_llm")


if __name__ == "__main__":
    unittest.main()
